In [1]:
%pylab inline
import rlcompleter, readline
readline.parse_and_bind('tab: complete')
from sklearn import grid_search
from sets import Set

Populating the interactive namespace from numpy and matplotlib


In [69]:
sift_train = np.load("CS5785-final-data/SIFTBoW_train.npy")
train = np.genfromtxt("CS5785-final-data/train.txt",dtype='str')
train_label = list(train[:,1])
file_name = list(train[:,0])

In [61]:
from sklearn.naive_bayes import MultinomialNB
from sklearn.naive_bayes import GaussianNB
from sklearn.naive_bayes import BernoulliNB
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC
from sklearn import cross_validation

In [45]:
mnb = MultinomialNB(alpha=0.1,fit_prior=True,class_prior=None)
#gnb = GaussianNB() very bad performance
bnb = BernoulliNB(alpha=0.1, binarize=0.0, fit_prior=True, class_prior=None)
mnb_score = cross_validation.cross_val_score(mnb,sift_train,train_label,cv=3)
#gnb_score = cross_validation.cross_val_score(gnb,sift_train,train_label,cv=3)
bnb_score = cross_validation.cross_val_score(bnb,sift_train,train_label,cv=3)

In [46]:
print mnb_score,bnb_score

[ 0.144  0.127  0.138] [ 0.146  0.135  0.133]


In [58]:
logistic = LogisticRegression(penalty='l2', dual=False, tol=0.01, C=1.0, fit_intercept=True, intercept_scaling=1, class_weight=None, random_state=None, solver='liblinear', max_iter=100, multi_class='ovr', verbose=0)
logistic_score = cross_validation.cross_val_score(logistic,sift_train,train_label,cv=3)

In [59]:
print logistic_score

[ 0.145  0.156  0.139]


In [56]:
knn = KNeighborsClassifier(n_neighbors=5, weights='distance', algorithm='kd_tree', leaf_size=30, p=2, metric='minkowski')
knn_score = cross_validation.cross_val_score(knn,sift_train,train_label,cv=3)

In [57]:
print knn_score

[ 0.079  0.092  0.083]


In [62]:
svn = SVC()
param_grid = [
  {'C': [0.01, 1, 10, 100, 1000, 10000], 'kernel': ['linear']},
  {'C': [0.01, 1, 10, 100, 1000, 10000], 'gamma': [0.001, 0.0001, 0.00001], 'kernel': ['rbf']},
 ]
clf = grid_search.GridSearchCV(svn, param_grid)
clf.fit(sift_train,train_label)
print clf.grid_scores_

[mean: 0.12167, std: 0.00776, params: {'kernel': 'linear', 'C': 0.01}, mean: 0.15333, std: 0.00189, params: {'kernel': 'linear', 'C': 1}, mean: 0.15333, std: 0.00189, params: {'kernel': 'linear', 'C': 10}, mean: 0.15333, std: 0.00189, params: {'kernel': 'linear', 'C': 100}, mean: 0.15333, std: 0.00189, params: {'kernel': 'linear', 'C': 1000}, mean: 0.15333, std: 0.00189, params: {'kernel': 'linear', 'C': 10000}, mean: 0.12333, std: 0.00776, params: {'kernel': 'rbf', 'C': 0.01, 'gamma': 0.001}, mean: 0.12167, std: 0.00776, params: {'kernel': 'rbf', 'C': 0.01, 'gamma': 0.0001}, mean: 0.12167, std: 0.00776, params: {'kernel': 'rbf', 'C': 0.01, 'gamma': 1e-05}, mean: 0.12333, std: 0.00776, params: {'kernel': 'rbf', 'C': 1, 'gamma': 0.001}, mean: 0.12167, std: 0.00776, params: {'kernel': 'rbf', 'C': 1, 'gamma': 0.0001}, mean: 0.12167, std: 0.00776, params: {'kernel': 'rbf', 'C': 1, 'gamma': 1e-05}, mean: 0.13200, std: 0.00638, params: {'kernel': 'rbf', 'C': 10, 'gamma': 0.001}, mean: 0.1216

In [74]:
print clf.best_params_

{'kernel': 'rbf', 'C': 100, 'gamma': 0.001}


[ 0.13750186  0.1690537   0.13164156 ...,  0.04393534  0.12083447
  0.12772153]
